mtfreepress/capitol-tracker-2025

next.config.mjs, src/components/bill/Actions.js
**In this PR**
1) Pull in the committeeHearingTime from our new actions data
2) If committeeHearingTime != null, we use that date for the action else we use the normal date
3) Fixed sorting so we sort by committeeHearingTime if it exists so we don't end up with an order where a committeeHearing scheduled on Jan 20th for the 27th as before an action on January 21st
=> Fix Date issue for hearings

inputs/lawmakers/committee-assignments-2025.csv, inputs/lawmakers/legislator-roster-2025.json, process/config/committees.js, process/functions.js, process/main.js, process/models/Lawmaker.js, src/components/lawmaker/Commitees.js
Note that I didn't commit updates to the data files here to avoid merge issues — I did run process locally for a check though.
A couple other things:
- Note that I added committee data lookup functions to `process/function.js`, which is intended to be a central place to stash utility-ish functions that could be used by multiple models in the processing system (e.g. when we get to matching bill actions to committees, we'll be in theory able to use the same set of utility functions to pull committee data from `inputs/committees/commitees/csv`). There's also stuff in there like a `capitalize()` function so we can write that once and use it across the processing framework.
- I also cleaned up some code you had that was doing similar processing inside the Lawmaker model.
- The `committeeKey` …
=> Fix lawmaker/committee matching so lawmaker pages display properly

process/config/committees.js, process/config/procedure.js, process/functions.js, process/main.js, process/models/Action.js, process/models/Bill.js
This fixes the (most of the) bugs we've been seeing with how actions are being mapped to bill progression. There's still a quirk on the reconciliation step on HB 1 that's attributable to a weird combination of bill actions.
I've also done a little bit of cleanup and documenting here and there, though the Bill `getProgress` logic is still a nightmare. In the mid-term, we should look at how the official site pizza tracker is set up and see if we can replace that logic to avoid what will be constant maintenance headaches.
=> Fix progression

inputs/lawmakers/legislator-roster-2025.json, inputs/lawmakers/legislator-session-history.json, inputs/lawmakers/roster-annotations.csv
**In this PR**:
1) Updates to `Mark Thane`, `Jamie Isaly` and `Debo Powers`
2) Mark and Jamie Locale changed via `annotations.csv`
3) Debo changed directly (removed 2019 from `sessions`)
=> updated lawmaker roster/annoations

src/components/bill/Actions.js
**In this PR**
1) Deal with a small single line change to fix styling for the bottom `Hide full vote breakdown` button on the bill pages.
=> Styling for `hide vote breakdown`

inputs/lawmakers/legislator-roster-2025.json, inputs/lawmakers/roster-annotations.csv
**In this PR**
1) Updated annotations to deal with the fact that official address is listed as the Capitol and thus `Helena`. Now says bozeman. 
2) Ran the `make-lawmaker-roster-2025.py` script to ensure it is picked up when the data pipeline runs
=> Cora Neumann Helena -> Bozeman

.github/workflows/data.yml, .github/workflows/refresh-all-pdfs.yml, inputs/nightly-full-refresh/fetch-all-bill-notes.js, nightly-pdf-refresh.sh
1. Add a `refresh-all-pdfs.yml` GHA script
a. Invokes a `nighly-pdf-refresh.sh` script
b. `nighly-pdf-refresh.sh` triggers a `fetch-all-bill-notes.js` file to grab all PDFs (rather than just grabbing those in the 
list we pass from the interface of ones that were updated on the most recent pass)
2. Change main refresh and redeploy to only happen from 5am to 11:59pm to give us some downtime to run a full refresh of all documents to ensure consistency
3. Changes support our changes to the `fetch-bill-notes.js` to ensure file consistency and no duplicates. 
1. Add a script to grab all PDF bill text
2. Add an incremental script like we have for `fetch-bill-notes.js`
=> Changes to GHA and adding a nightly refresh all pdfs

inputs/bills/fetch-bill-notes.js, inputs/bills/fetch.js, process/utils.js
1) Comment out logging from writeJson and writeCsv to make logs on GHA manageable. Spitting out nearly 7000 lines of `writing JSON` logs. 
2) Comment out logging for download file, comprising the rest of our unmanageable GHA logs.
3) Error handling left in place
=> Reduce Verbosity to make GHA logs usable

nightly-pdf-refresh.sh
1) `nightly-pdf-refresh.sh` now 
a) grabs all bill data, articles etc. 
b) deploys to AWS
2) Along with the previous full PDF refresh to ensure data integrity
3) Uses `measure_time` to display how long each step takes. 
1) Figure out what bills/fetch.js is throwing an error about ES modules while other seemingly identical scripts to fetch other things aren't. Not breaking anything so low priority.
=> Nightly refresh changes

src/components/bill/Actions.js
1) Add back committee names being displayed for hearings. 
2) Mirrored styling from 2023 guide
3) Will need to add links back once committee pages are fully fixed
=> Committee names displaying as expected 

src/components/input/LawmakerLookup.js, src/pages/index.js
1) Remove the `isActive` filtering from getStaticProps in `index.js` that is used for `LawmakerLookup`
2) Added an `Inactive` badge so it's clear to the user.
=> Stop filtering by isActive for LawmakerLookup.js

process/models/CalendarPage.js, src/components/CalendarNavigator.js, src/pages/calendar/[key].js, src/pages/lawmaker-cards/[key].js, src/pages/lawmakers/[key].js
1) `Floor Votes` and `Floor Debates` now get their own House and Senate subsection. 
2) Moved `Prev` `Go to today` & `Next` buttons. 
3) `Go to today` no longer shown when we are already on today. 
4) Small styling tweaks to make the buttons fit in nicely. 
5) `rm` a few console logs.
=> Calendar Tweaks

src/components/BillTable.js, src/config/utils.js
1) Add a util function `fetchBillsWithAmendments`
2) Modify `BillTable.js` to use it so that links only show when there is amendments
**TODO:**
1) Add interface for selecting from the amendment PDFs we are storing on our deployment rather than linking to the state's website tab with that bill's amendments.
=> Only show `proposed amendments` link for bills with amendments

process/models/CalendarPage.js
1) Add filtering for Canceled hearings so we don't display them on calendar
2) Creates a unique key for the hearing based on bill/committee/hearingTime and compares to actions we are considering adding to calendar. 
Old: 
New:
=> Canceled hearings

build-and-deploy.sh, public/document-index.json, scripts/generate-document-index.js
1) Using `npm run build` now to ensure that our `generate-document-index` script is run. 
2) Changed regex to keep the letter to make it easier to follow in the legislature while keeping the extra context of a "human-readable" part as well.
=> Fixes for amendment display

src/components/LawmakerTable.js
1) Fix that lawmaker image in `LawmakerTable.js` was a link to a larger version of the image. Now takes reader to lawmakers page. Most readers likely do not care to see a big photo of the lawmaker lol.
=> Lawmaker image links to lawmaker page

process/main.js, process/models/Committee.js, src/pages/calendar/[key].js
1) Committee data is now being processed and built again 🎉 
2) Fix processing of committees so now commas are removed 
ie no more: `senate,-business,-and-labor` just `senate-business-and-labor`
3) Fixes sorting of committees into AM/PM buckets
=> Fix Committees Calendar Display

process/main.js, process/models/Vote.js
**In this PR**
1) Handle the house blast motions not showing the proper vote threshold (passing at majority — needs 55)
=> House blast motion pass threshold

process/main.js, server.js, src/components/BillTable.js, src/config/utils.js, src/pages/bill-cards/[key].js, src/pages/bills/[key].js
**In this PR**
1) `process/main.js` now outputs a file for each bill
2) loadBillActions in `bill-cards` and `bills pages` now uses the single file for each bill. (Memory usage reduced from over 300MB to less than 50MB)
3) Modifications to reduce memory usage in `all-bills` from upwards of 1GB at times to around 250MB (there's a lot of bills)
4) `server.js` file runs the built version of the website properly now. Had some weird page issues before. Allowing for accurate debugging of a production build.
=> Fix excessive memory consumption on certain pages

.github/workflows/data.yml, README.md, process/config/procedure.js, process/config/session.js, process/models/Bill.js
**In this PR**
1) Add processing to handle post-session cleanup in `Bills.js`
2) Add/modify a few entries in `procedure.js` to compliment 
3) Add a `SESSION_END_DATE` to `/process/config/session.js` to tell processing when it is time for session end cleanup to occur
4) Added entry in `README.md` about `SESSION_END_DATE` so it doesn't cause issues for next session because the end date is nearly 2 years ago 
5) Modify GitHub Actions to run once an hour rather than every 20 minutes since the session is over — just waiting for gov to sign stuff
=> Fix Bills displaying improperly post session
